name: commentCommands

on:
  issue_comment:
    types: created
    
jobs:

  assign-commentor:
    runs-on: ubuntu-latest
    if: |
      contains(github.event.comment.body, '/assignme') ||
      contains(github.event.comment.body, '/assign me')
    steps:
      - name: Assigning to commenter
        run: |
          curl \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/assignees \
          -d '{"assignees":["${{ github.event.comment.user.login }}"]}'
  
  add-label-duplicate:
    runs-on: ubuntu-latest
    if: |
      contains(github.event.comment.body, '/duplicate') && (
      github.event.comment.author_association == 'OWNER' ||
      github.event.comment.author_association == 'COLLABORATOR' ||
      github.event.comment.author_association != 'CONTRIBUTOR' )
    steps:
      - name: add-label-duplicate
        run: |
          curl \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/labels \
              -d '{"labels":["duplicate"]}'

  add-label-documentation:
    runs-on: ubuntu-latest
    if: |
      contains(github.event.comment.body, '/documentation') && (
      github.event.comment.author_association == 'OWNER' ||
      github.event.comment.author_association == 'COLLABORATOR' ||
      github.event.comment.author_association != 'CONTRIBUTOR' )
    steps:
      - name: add-label-documentation
        run: |
          curl \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/labels \
              -d '{"labels":["documentation"]}'

  add-label-accessibility:
    runs-on: ubuntu-latest
    if: |
      contains(github.event.comment.body, '/accessibility') && (
      github.event.comment.author_association == 'OWNER' ||
      github.event.comment.author_association == 'COLLABORATOR' ||
      github.event.comment.author_association != 'CONTRIBUTOR' )
    steps:
      - name: add-label-accessibility
        run: |
          curl \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/labels \
              -d '{"labels":["accessibility"]}'

  add-label-help-wanted:
    runs-on: ubuntu-latest
    if: |
      (
      contains(github.event.comment.body, '/help me') ||
      contains(github.event.comment.body, '/need help') ||
      contains(github.event.comment.body, '/need some help') ||
      contains(github.event.comment.body, '/helpwanted') ||
      contains(github.event.comment.body, '/help wanted')
      ) && (
      github.event.comment.author_association == 'OWNER' ||
      github.event.comment.author_association == 'COLLABORATOR' ||
      github.event.comment.author_association != 'CONTRIBUTOR'
      )
    steps:
      - name: add-label-help-wanted
        run: |
          curl \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/labels \
              -d '{"labels":["help wanted"]}'

  add-label-good-first-issue:
    runs-on: ubuntu-latest
    if: |
      (
      contains(github.event.comment.body, '/goodfirstissue') ||
      contains(github.event.comment.body, '/good first issue')
      ) && (
      github.event.comment.author_association == 'OWNER' ||
      github.event.comment.author_association == 'COLLABORATOR' ||
      github.event.comment.author_association != 'CONTRIBUTOR'
      )
    steps:
      - name: add-label-good-first-issue
        run: |
          curl \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/labels \
              -d '{"labels":["good first issue"]}'

  add-label-enhancement:
    runs-on: ubuntu-latest
    if: |
      (
      contains(github.event.comment.body, '/enhancement') ||
      contains(github.event.comment.body, '/enhances') ||
      contains(github.event.comment.body, '/enhance')
      ) && (
      github.event.comment.author_association == 'OWNER' ||
      github.event.comment.author_association == 'COLLABORATOR' ||
      github.event.comment.author_association != 'CONTRIBUTOR'
      )
    steps:
      - name: add-label-good-first-issue
        run: |
          curl \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/labels \
              -d '{"labels":["enhancement"]}'

  request-issue-framing-improvement:
    runs-on: ubuntu-latest
    if: |
      contains(github.event.comment.body,'/improve') && (
      github.event.comment.author_association == 'OWNER' ||
      github.event.comment.author_association == 'COLLABORATOR' ||
      github.event.comment.author_association != 'CONTRIBUTOR' )
    steps:
      - name: request-issue-framing-improvement
        run: |
          curl \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments \
          -d '{"body":"This issue is put on hold due to low quality. No reviews or fixes will be performed at this time. Eventually, it will be closed. While we appreciate your effort writing, we are not able to further investigate it. Please improve it by writing a better title or providing more details, and you may re-open it."}'
