name: IssueCommentCommands

on:
  issue_comment:
    types: created
    
jobs:

  assign-commentor:
    runs-on: ubuntu-latest
    if: |
      contains(github.event.comment.body, '/assignme')
    steps:
      - name: Assigning to commenter
        run: |
          curl \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/assignees \
          -d '{"assignees":["${{ github.event.comment.user.login }}"]}'
  
  add-label-duplicate:
    runs-on: ubuntu-latest
    if: |
      contains(github.event.comment.body, '/duplicate') && (
      github.event.comment.author_association == 'OWNER' ||
      github.event.comment.author_association == 'COLLABORATOR' ||
      github.event.comment.author_association == 'CONTRIBUTOR' )
    steps:
      - name: add-label-duplicate
        run: |
          curl \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/labels \
              -d '{"labels":["duplicate"]}'

  add-label-documentation:
    runs-on: ubuntu-latest
    if: |
      contains(github.event.comment.body, '/documentation') && (
      github.event.comment.author_association == 'OWNER' ||
      github.event.comment.author_association == 'COLLABORATOR' ||
      github.event.comment.author_association == 'CONTRIBUTOR' )
    steps:
      - name: add-label-documentation
        run: |
          curl \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/labels \
              -d '{"labels":["documentation"]}'

  add-label-accessibility:
    runs-on: ubuntu-latest
    if: |
      contains(github.event.comment.body, '/accessibility') && (
      github.event.comment.author_association == 'OWNER' ||
      github.event.comment.author_association == 'COLLABORATOR' ||
      github.event.comment.author_association == 'CONTRIBUTOR' )
    steps:
      - name: add-label-accessibility
        run: |
          curl \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/labels \
              -d '{"labels":["accessibility"]}'
